name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Download
      run: |
        curl -O https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip
        unzip ngrok-stable-darwin-amd64.zip

    - name: Auth
      run: |
        echo "Authenticating ngrok..."
        ./ngrok/ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable VNC
      run: |
        echo "Enabling VNC..."
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -users runneradmin -privs -all -restart -agent -menu

    - name: Create Tunnel
      run: |
        echo "Creating ngrok tunnel for VNC..."
        ./ngrok/ngrok tcp 5900
