name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Download ngrok
      run: |
        curl -O https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip
        unzip ngrok-stable-darwin-amd64.zip

    - name: Enable VNC without Password
      run: |
        echo "Enabling VNC without password..."
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -users runneradmin -privs -all -restart -agent -menu -clientopts -setreqprot -protocol 3.3 -setvnclegacy -vnclegacy yes

    - name: Authenticate ngrok
      run: |
        echo "Authenticating ngrok..."
        ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Create ngrok Tunnel for VNC
      run: |
        echo "Creating ngrok tunnel for VNC..."
        ./ngrok tcp 5900
