name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Download
      run: |
        curl -O https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.zip
        unzip ngrok-stable-darwin-amd64.zip

    - name: Set Password
      run: |
        echo "Setting VNC password..."
        echo "P@ssw0rd!" > vncpassword.txt
      env:
        VNC_PASSWORD_FILE: vncpassword.txt

    - name: Enable VNC
      run: |
        echo "Enabling VNC..."
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -access -on -users runneradmin -privs -all -restart -agent -menu -clientopts -setreqprot -protocol 3.3 -setvnclegacy -vnclegacy yes -clientopts -setvncpw -vncpw $VNC_PASSWORD_FILE

    - name: Create Tunnel
      run: |
        echo "Creating ngrok tunnel for VNC..."
        ./ngrok tcp 5900
